{
    "url": "https://api.github.com/repos/thundernest/k-9/issues/5343",
    "repository_url": "https://api.github.com/repos/thundernest/k-9",
    "labels_url": "https://api.github.com/repos/thundernest/k-9/issues/5343/labels{/name}",
    "comments_url": "https://api.github.com/repos/thundernest/k-9/issues/5343/comments",
    "events_url": "https://api.github.com/repos/thundernest/k-9/issues/5343/events",
    "html_url": "https://github.com/thundernest/k-9/issues/5343",
    "id": 921203857,
    "node_id": "MDU6SXNzdWU5MjEyMDM4NTc=",
    "number": 5343,
    "title": "issue with \"Add from Contact\" when permission not granted",
    "user": {
        "login": "rezazarchi",
        "id": 8654398,
        "node_id": "MDQ6VXNlcjg2NTQzOTg=",
        "avatar_url": "https://avatars.githubusercontent.com/u/8654398?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/rezazarchi",
        "html_url": "https://github.com/rezazarchi",
        "followers_url": "https://api.github.com/users/rezazarchi/followers",
        "following_url": "https://api.github.com/users/rezazarchi/following{/other_user}",
        "gists_url": "https://api.github.com/users/rezazarchi/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/rezazarchi/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/rezazarchi/subscriptions",
        "organizations_url": "https://api.github.com/users/rezazarchi/orgs",
        "repos_url": "https://api.github.com/users/rezazarchi/repos",
        "events_url": "https://api.github.com/users/rezazarchi/events{/privacy}",
        "received_events_url": "https://api.github.com/users/rezazarchi/received_events",
        "type": "User",
        "site_admin": false
    },
    "labels": [
        {
            "id": 187334212,
            "node_id": "MDU6TGFiZWwxODczMzQyMTI=",
            "url": "https://api.github.com/repos/thundernest/k-9/labels/bug",
            "name": "bug",
            "color": "e11d21",
            "default": true,
            "description": null
        }
    ],
    "state": "closed",
    "locked": false,
    "assignee": null,
    "assignees": [],
    "milestone": null,
    "comments": 1,
    "created_at": "2021-06-15T09:36:41Z",
    "updated_at": "2021-06-17T19:34:11Z",
    "closed_at": "2021-06-17T19:34:11Z",
    "author_association": "CONTRIBUTOR",
    "active_lock_reason": null,
    "body": "I have some issues when i don't give contact permission to application and Add from Contacts.\r\n\r\n**Describe the bug**\r\nOn Android 11 toast showed with this message: **No email address could be found for this contact.**\r\nOn Android 7 & 9 contact added successfully but when i click on that in To field, application get crashed.\r\n\r\n**To Reproduce**\r\nSteps to reproduce the behavior:\r\n\r\n1. Don't give contact permission\r\n2. Go to \"Compose''\r\n2. Click on 'more options then Add from Contacts'\r\n3. Select a contact\r\n4.1. On Android 11 toast showed with this message: **No email address could be found for this contact.**\r\n4.2. On Android 7 & 9 contact added successfully but when i click on that name or email in To field, application get crashed.\r\n\r\n**Expected behavior**\r\nmaybe should not show \"Add from Contacts\" when there is no contact permission or handle these situations and show related error message to the user.\r\n\r\n**Environment (please complete the following information):**\r\n - K-9 Mail version: 5.735-SNAPSHOT\r\n - Android version: 7,9,11\r\n - Device: Emulator\r\n - Account type: IMAP\r\n\r\n**ScreenShot**\r\nAndroid 7\r\nhttps://user-images.githubusercontent.com/8654398/122031636-21e7a980-cde4-11eb-872e-bd550c076d13.mp4\r\n\r\n**Logs**\r\nerror log on Android 7\r\n```\r\n2021-06-15 14:06:09.330 3649-3724/com.fsck.k9.debug E/AndroidRuntime: FATAL EXCEPTION: ModernAsyncTask #4\r\n    Process: com.fsck.k9.debug, PID: 3649\r\n    java.lang.RuntimeException: An error occurred while executing doInBackground()\r\n        at androidx.loader.content.ModernAsyncTask$3.done(ModernAsyncTask.java:164)\r\n        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)\r\n        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)\r\n        at java.util.concurrent.FutureTask.run(FutureTask.java:242)\r\n        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)\r\n        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)\r\n        at java.lang.Thread.run(Thread.java:761)\r\n     Caused by: java.lang.SecurityException: Permission Denial: reading com.android.providers.contacts.ContactsProvider2 uri content://com.android.contacts/contacts/lookup/0r1-4B315B29/1 from pid=3649, uid=10082 requires android.permission.READ_CONTACTS, or grantUriPermission()\r\n        at android.os.Parcel.readException(Parcel.java:1683)\r\n        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)\r\n        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)\r\n        at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)\r\n        at android.content.ContentResolver.query(ContentResolver.java:530)\r\n        at android.content.ContentResolver.query(ContentResolver.java:472)\r\n        at android.provider.ContactsContract$Contacts.lookupContact(ContactsContract.java:1623)\r\n        at com.fsck.k9.activity.compose.RecipientLoader.fillContactDataFromLookupKey(RecipientLoader.java:284)\r\n        at com.fsck.k9.activity.compose.RecipientLoader.loadInBackground(RecipientLoader.java:201)\r\n        at com.fsck.k9.activity.compose.RecipientLoader.loadInBackground(RecipientLoader.java:37)\r\n        at androidx.loader.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:307)\r\n        at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:60)\r\n        at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:48)\r\n        at androidx.loader.content.ModernAsyncTask$2.call(ModernAsyncTask.java:141)\r\n        at java.util.concurrent.FutureTask.run(FutureTask.java:237)\r\n        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)\u00a0\r\n        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)\u00a0\r\n        at java.lang.Thread.run(Thread.java:761)\r\n```\r\n\r\n",
    "closed_by": {
        "login": "cketti",
        "id": 218061,
        "node_id": "MDQ6VXNlcjIxODA2MQ==",
        "avatar_url": "https://avatars.githubusercontent.com/u/218061?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/cketti",
        "html_url": "https://github.com/cketti",
        "followers_url": "https://api.github.com/users/cketti/followers",
        "following_url": "https://api.github.com/users/cketti/following{/other_user}",
        "gists_url": "https://api.github.com/users/cketti/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/cketti/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/cketti/subscriptions",
        "organizations_url": "https://api.github.com/users/cketti/orgs",
        "repos_url": "https://api.github.com/users/cketti/repos",
        "events_url": "https://api.github.com/users/cketti/events{/privacy}",
        "received_events_url": "https://api.github.com/users/cketti/received_events",
        "type": "User",
        "site_admin": false
    },
    "reactions": {
        "url": "https://api.github.com/repos/thundernest/k-9/issues/5343/reactions",
        "total_count": 0,
        "+1": 0,
        "-1": 0,
        "laugh": 0,
        "hooray": 0,
        "confused": 0,
        "heart": 0,
        "rocket": 0,
        "eyes": 0
    },
    "timeline_url": "https://api.github.com/repos/thundernest/k-9/issues/5343/timeline",
    "performed_via_github_app": null,
    "state_reason": "completed"
}